config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts
  get 'about' => 'public#about', as: :about
  get 'blog' => 'public#blog', as: :blog
  get 'contact' => 'public#contact', as: :contact

  resources :posts
  post "post/view" => "posts#save_post_view", as: :post_view 

  root to: "public#homepage"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :title, :url
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :summary, presence: true, length: { maximum: 200}
  validates :body, presence: true, length: { minimum: 100}
  validates :active, inclusion: [true, false]

  # belongs_to :user
  belongs_to :category
  belongs_to :account
  # has_many :comments

  # if terms and conditions need to be true
  # validates :terms_of_service, acceptance: true

  # number validation
  # validates :rating, numericality: true
  # validates :views, numericality: { only_integer: true}

  # callbacks - validation / save / create / update / destroy
  after_create :update_total_posts_count

  scope :active, -> { where( active: true )}
  scope :order_by_latest_first, -> { order( created_at: :desc ) }
  scope :limit_5, -> { limit(5)}


  # instance method
  def details
    "This post was created by #{created_by} on #{ created_at.strftime('%d.%m.%Y') }"
  end

  # class method
  def self.total
    # returns total number of posts
    count
  end

  private

  def update_total_posts_count
    category.increment(:total_count, 1).save
  end

  def created_by
    return "Admin" unless account
    "#{account.first_name} #{account.last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, except: [:show]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :save_post_view]
  before_action :can_modify_post, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    respond_to do |format|
      format.html
      format.json { 
        render json: @post.to_json
      }
      format.text { 
        render plain: @post.title
      }
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.account_id = current_account.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def save_post_view
    # store view count for post
    @post.increment(:views, 1).save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def can_modify_post
      redirect_back(fallback_location: root_path) and return unless @post.account_id == current_account.id
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :summary, :body, :category_id, :active)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  def homepage
    @posts = Post.active.order_by_latest_first.limit_5
    @categories = Category.all
  end

  def about
  end

  def blog
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title title
    content_for :page_title, title.to_s
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def my_helper_method
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_meta post
    "Created #{time_ago_in_words(post.created_at)} ago within #{post.category.title}. Post has been viewed #{post.views} times."
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container d-flex justify-content-center mt-2">
  Copyright &copy <%= Date.current.strftime("%Y") %>
  </div>
</footer>

app/views/layouts/_form_validation.html.erb
  <% if local_assigns[:item] && item.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg justify-content-between navbar-light bg-light">
  <a class="navbar-brand" href="#">My blog</a>
  <div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'Home', root_url, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Blog', blog_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact', contact_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <% if account_signed_in? %>
            <%= link_to 'Sign Out', destroy_account_session_path, method: :delete, class: 'nav-link' %>
          <% else %>
            <%= link_to 'Sign In', new_account_session_path, class: 'nav-link' %>
          <% end%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:page_title) ? yield(:page_title) : "Ruby on Rails" %> | My Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <%# same as render partial: "layouts/menu" %>
    <%= render "layouts/menu"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <div class="row">
        <div class="col mt-5">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= @name if @name.present? %>
    <%= render partial: "layouts/footer"%>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <%= render partial: "layouts/form_validation", locals: { item: post } %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :summary %>
    <%= form.text_field :summary %>
  </div>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <div class="field">
    <%= form.label :category %>
    <%= form.select :category_id, Category.all.collect{|c| [c.title, c.id]} %>
  </div>
  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
  <% if local_assigns[:post]%>
  <h3> <%= link_to post.title, post_path(post) %> </h3>
  <%= post_meta post%>
  <p> <%=  post.summary %> </p>
<% end %>

app/views/posts/_view_form.html.erb
<%= form_with(url: post_view_path, html: {id: "save_views"}) do |form| %>
  <%= form.hidden_field :id, value: post.id %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Summary</th>
      <th>Body</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.summary %></td>
        <td><%= post.body %></td>
        <td><%= post.active %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  <%= @post.title %>
</h1>
<small><%= @post.details %></small>
<p>
  <%= simple_format @post.body %>
</p>
<%= render partial: "posts/view_form", locals: {post: @post} %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', root_url %>